spring:
  config:
    import: "optional:classpath:application-local.yml"

  datasource:
    url: jdbc:postgresql://localhost:5432/accountbook
    username: bookadmin
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  app-redirect-uri: ${KAKAO_APP_REDIRECT_URI}